# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dev/Code/C/Connery/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dev/Code/C/Connery

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dev/Code/C/Connery/CMakeFiles /home/dev/Code/C/Connery/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dev/Code/C/Connery/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Connery

# Build rule for target.
Connery: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Connery
.PHONY : Connery

# fast build rule for target.
Connery/fast:
	$(MAKE) -f CMakeFiles/Connery.dir/build.make CMakeFiles/Connery.dir/build
.PHONY : Connery/fast

cval.o: cval.c.o

.PHONY : cval.o

# target to build an object file
cval.c.o:
	$(MAKE) -f CMakeFiles/Connery.dir/build.make CMakeFiles/Connery.dir/cval.c.o
.PHONY : cval.c.o

cval.i: cval.c.i

.PHONY : cval.i

# target to preprocess a source file
cval.c.i:
	$(MAKE) -f CMakeFiles/Connery.dir/build.make CMakeFiles/Connery.dir/cval.c.i
.PHONY : cval.c.i

cval.s: cval.c.s

.PHONY : cval.s

# target to generate assembly for a file
cval.c.s:
	$(MAKE) -f CMakeFiles/Connery.dir/build.make CMakeFiles/Connery.dir/cval.c.s
.PHONY : cval.c.s

hashtable.o: hashtable.c.o

.PHONY : hashtable.o

# target to build an object file
hashtable.c.o:
	$(MAKE) -f CMakeFiles/Connery.dir/build.make CMakeFiles/Connery.dir/hashtable.c.o
.PHONY : hashtable.c.o

hashtable.i: hashtable.c.i

.PHONY : hashtable.i

# target to preprocess a source file
hashtable.c.i:
	$(MAKE) -f CMakeFiles/Connery.dir/build.make CMakeFiles/Connery.dir/hashtable.c.i
.PHONY : hashtable.c.i

hashtable.s: hashtable.c.s

.PHONY : hashtable.s

# target to generate assembly for a file
hashtable.c.s:
	$(MAKE) -f CMakeFiles/Connery.dir/build.make CMakeFiles/Connery.dir/hashtable.c.s
.PHONY : hashtable.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/Connery.dir/build.make CMakeFiles/Connery.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/Connery.dir/build.make CMakeFiles/Connery.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/Connery.dir/build.make CMakeFiles/Connery.dir/main.c.s
.PHONY : main.c.s

mpc.o: mpc.c.o

.PHONY : mpc.o

# target to build an object file
mpc.c.o:
	$(MAKE) -f CMakeFiles/Connery.dir/build.make CMakeFiles/Connery.dir/mpc.c.o
.PHONY : mpc.c.o

mpc.i: mpc.c.i

.PHONY : mpc.i

# target to preprocess a source file
mpc.c.i:
	$(MAKE) -f CMakeFiles/Connery.dir/build.make CMakeFiles/Connery.dir/mpc.c.i
.PHONY : mpc.c.i

mpc.s: mpc.c.s

.PHONY : mpc.s

# target to generate assembly for a file
mpc.c.s:
	$(MAKE) -f CMakeFiles/Connery.dir/build.make CMakeFiles/Connery.dir/mpc.c.s
.PHONY : mpc.c.s

util.o: util.c.o

.PHONY : util.o

# target to build an object file
util.c.o:
	$(MAKE) -f CMakeFiles/Connery.dir/build.make CMakeFiles/Connery.dir/util.c.o
.PHONY : util.c.o

util.i: util.c.i

.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) -f CMakeFiles/Connery.dir/build.make CMakeFiles/Connery.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s

.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) -f CMakeFiles/Connery.dir/build.make CMakeFiles/Connery.dir/util.c.s
.PHONY : util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Connery"
	@echo "... edit_cache"
	@echo "... cval.o"
	@echo "... cval.i"
	@echo "... cval.s"
	@echo "... hashtable.o"
	@echo "... hashtable.i"
	@echo "... hashtable.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mpc.o"
	@echo "... mpc.i"
	@echo "... mpc.s"
	@echo "... util.o"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

